version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://admin:admin@database:5432/quizzbuilder
      - REDIS_HOST=localhost
    depends_on:
      - database
    networks:
      - backend
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=quizzbuilder
    ports:
      - 5432:5432
    networks:
      - backend
  redis:
    image: redis
    container_name: redis
    restart: always
    command: ['redis-server', '--requirepass', '123456']
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge
