version: '3'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=quizzbuilder
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
